### ISSUE TITLE
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 10, current size 0)

### ISSUE THREAD

**Issue by 18801109112** [carrenD/Medical-Cross-Modality-Domain-Adaptation#23]
Thank for your code first.
But I meet the question like this.
I try every solution such 
Change relative path to absolute path
Change the num_threads and others

It confused me many days.
Should  I change the list of "mr_val_list" or others?
Thank you for your answers!!!

**Comment by cheng-01037** [comment]
This is quite a common issue. In short, the `mr_val_list` contains a list of path of image slices in the format of `tfrecords`. This error usually happens when the file paths for such tfrecords are incorrect. One way to debug it is to pull that part out and see if the queue runs normally and if the file paths can be read by the queue.

**Comment by Faunder-fld** [comment]
Here the best answer I had ever found: [https://github.com/carrenD/ummkd/issues/9](https://github.com/carrenD/ummkd/issues/9)
